Countries = {
    "Albania": "Tirana",
    "Austria": "Vienna",
    "Germany": "Berlin",
    "Australia": "Canberra",
    "Denmark": "Copenhagen",
    "Cuba": "Havana",
    "Greece": "Athens",
    "Hungary": "Budapest",
    "Romania": "Bucharest",
    "Poland": "Warsaw",
    "Czech Republic": "Prague",
    "France": "Paris",
    "Belgium": "Brussel",
    "Netherlands": "Amsterdam",
    "Luxembourg": "Luxembourg",
    "Switzerland": "Berne",
    "Norway": "Oslo",
    "Sweden": "Stockholm",
    "Finland": "Helsinki",
    "Estonia": "Tallinn",
    "Latvia": "Riga",
    "Lithuania": "Vilnius",
    "Belarus": "Minsk",
    "Ukraine": "Kiev",
    "Moldova": "Chizinau",
    "Russia": "Moscow",
    "Italy": "Rome",
    "Andorra": "Andorra la Vella",
    "Monaco": "Monaco",
    "San Marino": "San Marino",
    "Croatia": "Zagreb",
    "United Kingdom": "London",
    "Ireland": "Dublin",
    "Spain": "Madrid",
    "Iceland": "Reykjavik",
    "Portugal": ["Lisbon", "Lisboa"],
    "Bosnia": "Sarajevo",
    "Montenegro": "Podgorica",
    "Serbia": "Belgrade",
    "Kosovo": "Pristina",
    "North Macedonia": "Skopje",
    "Bulgaria": "Sofia",
    "Turkey": "Ankara",
    "China": "Beijing",
}